### ISSUE TITLE
Reload all commands

### ISSUE THREAD

**Issue by drillskibo** [PopperDevs/PopperBot#1]
Need to manage `commands rl all` in order to reload all commands at once.
The `Map.forEach()` doesn't seem to work, it reloads over and over, ad infinitum.

**Comment by johanneslosch** [comment]
why is the bug a still an issue if it is invalid?

**Comment by drillskibo** [comment]
I need to change the current code to make it work. I am not sure yet why the commented part errors.
Feel free to try it out yourself if you have an idea of what's causing the issue.
