### ISSUE TITLE
Automatisation

### ISSUE THREAD

**Issue by johanneslosch** [PopperDevs/PopperBot#15]
We could use GitHub actions to add some tests or build a package at the main branch, what do you think about that? 
ATM would I assign myselt since I have already have an opportunity to test GitHub Actions locally.

**Comment by jatin2003** [comment]
That'll be Great :smile:

**Comment by johanneslosch** [comment]
> That'll be Great smile
@jatin2003 do you have other ideas except of npm test`

**Comment by drillskibo** [comment]
[PR #16](https://github.com/PopperDevs/PopperBot/pull/16) fixed this issue.
