### ISSUE TITLE
Yarn vs NPM 

### ISSUE THREAD

**Issue by jodylecompte** [PopperDevs/PopperBot#32]
Currently we have both a package-lock.json (NPM) file as well as a yarn.lock (Yarn) file. It is ill-advised to have both. 

We should hold a vote on which package manager we will recommend for this project and delete the other lock file.

**Comment by jodylecompte** [comment]
Upvote for Yarn

**Comment by jodylecompte** [comment]
Upvote for NPM

**Comment by drillskibo** [comment]
I can list a few cons to using `yarn`, such as :
- Using `yarn` would mess with GitHub Actions;
- Most hosting platforms use `npm`.

**Comment by drillskibo** [comment]
[PR #34](https://github.com/PopperDevs/PopperBot/pull/34) was merged.
